import '/styles/globals.css';
import "react-loading-skeleton/dist/skeleton.css";
import {Vazirmatn} from "next/font/google";

const vazir = Vazirmatn ({
  subsets: ["arabic","latin"] ,
  display : "swap",

})

export const metadata = {
  title: 'Job Recomendation system',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,about }) {
  // throw new Error();
  return (
    <html lang="fa-IR"dir="rtl"classname ={vazir.classname} >
      <body >
        {children}
        {about}
      </body>
    </html>
  )
}
